### ISSUE TITLE
Home, About, Add my Work

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_explore#26]
The top left header in the current Explore looks like this:
![Screen Shot 2022-06-10 at 10 33 43 AM](https://user-images.githubusercontent.com/32677188/173088708-75b3ea64-6e43-4334-9aca-8e9e138db59c.png)

'Home' takes us to '/', 'About' takes us to an about page (will need wording for this), and 'Add my Work' takes us over to ETDA Workflow's '/' page.

**Comment by ajkiessl** [comment]
We may want to scrap the about page.  It mostly just describes the workflow process.

**Comment by jrpatterson** [comment]
@ajkiessl   I would leave these sections:
About the Graduate School eTD database.
Expand Creative Possibilities

They describe why the application exists.   

Please remove the remaining sections.  They describe the Workflow process and they already exist in the "About" page for that project.

**Comment by ajkiessl** [comment]
I didn't add a Home button.  I don't think that's necessary since there really isn't a home page.
