### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_explore#87]
The plan is to release from 8-9am on Thursday (7/28).  Depending on how long the rsync script will take, we'll need about an hour of downtime.

release steps: https://sites.psu.edu/dltdocs/?p=6258

**Comment by whereismyjetpack** [comment]
In nagios, do a find and replace on `objects/dsrd/etda-k8s.cfg` for `.k8s.libraries.psu.edu` and change to `.libraries.psu.edu`

**Comment by whereismyjetpack** [comment]
@ajkiessl I added these items into the sites doc so we don't forget them
